### ISSUE TITLE
How to withdraw  Stack Token (Dapp) 

### ISSUE THREAD

**Issue by tontheonelove** [ahmetozlu/defi_yield_farming#2]
How to withdraw  Stack Token (Dapp)   when Unstack

**Comment by ahmetozlu** [comment]
When you click "UN-STAKE..." button on the front-end application:

- [onClick](https://github.com/ahmetozlu/defi_yield_farming/blob/main/src/components/Main.js#L47) method of "UN-STAKE..." button calls [unstakeTokens()](https://github.com/ahmetozlu/defi_yield_farming/blob/main/src/contracts/TokenFarm.sol#L45) function.
- [unstakeTokens()](https://github.com/ahmetozlu/defi_yield_farming/blob/main/src/contracts/TokenFarm.sol#L45) function performs the operation for unstaking the tokens (withdraw).
